Condense database character classes
knsjerome/cmpt-354-project pull request #100
Opened 2021-04-10 21:50 UTC by knsjerome

2021-04-10 21:58 UTC, drowsell approved these changes
Looks good. Quick work!

2021-04-11 03:05 UTC, merged

2021-04-11 03:13 UTC, ksmolko requested changes

2021-04-11 03:13 UTC, ksmolko commented on server/sql/init_db.sql
> +    class_attribute     text CHECK (length(class_attribute) > 0) NOT NULL,
I was thinking we could combine all the enums below into one, and then make this attribute of type `e_class_attribute` or something like that. That would remove the need for length checking.

2021-04-11 03:13 UTC, ksmolko commented on server/sql/init_db.sql
> +    class_attribute     text CHECK (length(class_attribute) > 0) NOT NULL,
Also, if you were to do that, be sure to add "None" as an option as well (for players to select "None" as their class).

2021-04-11 03:13 UTC, ksmolko commented on server/sql/init_db.sql
> +    class_attribute     text CHECK (length(class_attribute) > 0) NOT NULL,
Otherwise, it would make sense to just remove all the enums below as they are unused.

2021-04-11 03:15 UTC, ksmolko commented
Lol looks like I was too late. Perhaps we should follow-up on this?

2021-04-11 03:46 UTC, knsjerome commented
> 
> 
> Lol looks like I was too late. Perhaps we should follow-up on this?

Yeah it looks your comments went through about 7-8 minutes after the merge.

The Go code currently validates the value going into the `class_attribute` field, so we should be good to remove the enums from that database or combine them.