UI development
knsjerome/cmpt-354-project pull request #31
Opened 2021-03-16 03:12 UTC by drowsell

Added my work in progress changes to the UI. I am using cards for the different field to keep things consistent and clean. I added the sliders and will add dropdown menus next. I will organize the cards at the end. Right now I am just getting all the fields written. 

I did not mean to change line 23 in client/src/router/index.js is there a way to reject only that change in git?

2021-03-16 03:20 UTC, knsjerome commented on client/src/views/Characters.vue
> +                </v-card>
Should be indented one less level to align with the opening `v-card` tag

2021-03-16 03:21 UTC, knsjerome commented on client/src/views/Characters.vue
> +      stat_sliders: [
This is nitpicky, but so far `camelCase` naming has been used in the project, let's try to keep it consistent

2021-03-16 03:22 UTC, knsjerome commented on client/src/views/Characters.vue
> +                  <!-- <div class="subtitle-1">Subtext</div> -->
Remove this if not used

2021-03-16 03:23 UTC, knsjerome commented on client/src/views/Characters.vue
> +                        v-model="blue"
Where is `blue` declared? I suspect you have an error that shows up in the developer console

2021-03-16 03:23 UTC, knsjerome commented on client/src/views/Home.vue
> +  <h1>Home</h1>
The items inside the `div` should be indented

2021-03-16 03:27 UTC, knsjerome requested changes
So far we've been using a 2-space indent for Vue files. It appears that you have been using 4. This should be enforced by `.editorconfig` (perhaps you need the VSCode extension installed?`

2021-03-16 03:36 UTC, knsjerome commented on client/src/views/Characters.vue
> +        { attribute: 'Dexterity' },
Since these names are visible to the user, you may wish to omit the underscores

2021-03-16 03:39 UTC, knsjerome commented on client/src/views/Characters.vue
> +                        type="number"
`type="number"` is unlikely to function that way you think it will. First, it adds the horrendously ugly up/down arrow to the input box. Second, the data type used by the text field is a `String` (I think), so we will need to manually convert the value to an integer value.

2021-03-16 03:42 UTC, knsjerome commented on client/src/views/Characters.vue
> +                        type="number"
Probably can leave as `type="text"` for now and we can deal with manual conversion later

2021-03-17 16:01 UTC, drowsell commented on client/src/views/Home.vue
> +  <h1>Home</h1>
Changed

2021-03-17 16:01 UTC, drowsell commented on client/src/views/Characters.vue
> +        { attribute: 'Dexterity' },
Fixed

2021-03-17 16:03 UTC, drowsell commented on client/src/views/Characters.vue
> +                        type="number"
Changed to type="text".

2021-03-17 16:07 UTC, drowsell commented
Pushed new code. This should be good to be pulled.

2021-03-17 16:13 UTC, drowsell commented
One thing to look at is client/package-lock.json is it normal for that to change?

2021-03-17 20:37 UTC, knsjerome commented on client/package-lock.json
> +  "lockfileVersion": 2,
I think you have a new version of npm, which causes this to happen

2021-03-17 20:47 UTC, drowsell commented on client/package-lock.json
> +  "lockfileVersion": 2,
Can you direct me to the version of npm you are using so I can match

2021-03-17 20:50 UTC, knsjerome commented on client/package-lock.json
> +  "lockfileVersion": 2,
6.14.8

2021-03-17 22:09 UTC, knsjerome approved these changes

2021-03-17 22:09 UTC, merged