Add to populate
knsjerome/cmpt-354-project pull request #39
Opened 2021-03-19 05:18 UTC by spacebugs

Finished script to populate all tables. This includes players so you may have to have a fresh db before running it.

2021-03-19 05:32 UTC, knsjerome commented on server/sql/populate_db.sql
> +('ae1', 'password1', 'Albert Einstein'),
Plain-text passwords should never be stored. Please go through the effort to getting these passwords hashed via the Go code and then you can copy-paste the hashed values into this insert statement.

2021-03-19 05:33 UTC, knsjerome requested changes
Hash the passwords before storing them

2021-03-19 05:44 UTC, ksmolko commented on server/sql/populate_db.sql
> +('ae1', 'password1', 'Albert Einstein'),
One other thing: If we are going to paste the hashed passwords into the SQL script here, then we should remove the following lines here: https://github.com/knsjerome/cmpt-354-project/blob/master/server/tests.go#L22-L26

2021-03-19 06:10 UTC, ksmolko commented on server/sql/populate_db.sql
> +)
Should have a comma here

2021-03-19 06:12 UTC, ksmolko commented on server/sql/init_db.sql
> +    'Druidic Warrior',
Oops thanks for catching this lol

2021-03-19 06:41 UTC, ksmolko approved these changes

2021-03-21 06:52 UTC, knsjerome approved these changes

2021-03-21 06:53 UTC, merged