Backend for "New Campaign" page
knsjerome/cmpt-354-project pull request #70
Opened 2021-04-04 01:28 UTC by ksmolko

Created entity models and functions for "Campaign" and "BelongsTo" relations. This is part of the work needed for #45.

2021-04-04 01:39 UTC, knsjerome requested changes

2021-04-04 01:39 UTC, knsjerome commented on .gitignore
> +*.yml~
Out of curiosity, where did these file extensions come from?

2021-04-04 01:39 UTC, knsjerome commented on server/routes.go
> +	r.POST("/newcampaign", app.createCampaign)
In my opinion, a more REST-like endpoint would simple be `"/campaign"`. The POST verb would imply that a new campaign is being created.

2021-04-04 01:39 UTC, knsjerome commented on server/handlers.go
> +			"/newcampaign/" + strconv.Itoa(id),
If the endpoint gets changed to "/campaign", update this as well.

2021-04-04 04:24 UTC, ksmolko commented on .gitignore
> +*.yml~
For some reason I had a config.yml~. I think it might have been an artifact from one of my text editors, probably notepad++ or vim.

2021-04-04 04:27 UTC, ksmolko commented on server/routes.go
> +	r.POST("/newcampaign", app.createCampaign)
The reason why I named it `/newcampaign` was to differentiate between the "Create new campaign" page, and the "Campaign status" page, which I would use `/campaign` for. Though I'm not quite sure if we're still planning on making a separate endpoint for campaign status, or just integrating it within the dashboard?

2021-04-04 04:57 UTC, knsjerome commented on server/routes.go
> +	r.POST("/newcampaign", app.createCampaign)
From what I understand, on the dashboard page the "campaign" tab will simply use a GET request and display data accordingly. This will probably involve some query related to getting all campaigns in which a given character is enrolled into, then displaying the campaign's `state` , `current_location` and `name` attributes in a card or something.

2021-04-04 05:27 UTC, ksmolko commented on server/routes.go
> +	r.POST("/newcampaign", app.createCampaign)
Sounds good, I've renamed it now.

2021-04-05 19:48 UTC, knsjerome approved these changes

2021-04-06 00:31 UTC, merged